version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    ports: ['9200:9200']
    volumes:
      - './var/elasticsearch:/usr/share/elasticsearch/data'

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.2
    container_name: logstash
    ports: ['9600:9600']
    depends_on: ['elasticsearch']
    volumes:
      - './etc/logstash/pipeline:/usr/share/logstash/pipeline'
      - './var/logs:/logs'

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.2
    container_name: filebeat
    user: root
    volumes:
      - './var/filebeat/log/:/var/log/:ro'
      - './var/filebeat/docker.sock:/var/run/docker.sock'
      - './var/logs/:/var/lib/docker/containers/logs:ro'
      - './etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
    command: ["--strict.perms=false"]

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.2
    container_name: kibana
    ports: ['5601:5601']
    depends_on:
      - 'elasticsearch'

