services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.0
    container_name: elasticsearch
    ports: [ '9200:9200' ]
    env_file:
      - path: ./env/.env
        required: true
      - path: ./env/.elastic.env
        required: false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './volumes/elasticsearch:/usr/share/elasticsearch/data'

  php:
    image: composer:2.8.8
    command: tail -f /dev/null
    volumes:
      - './app/php:/app'
      - './volumes/php/vendor:/app/vendor'
      - './volumes/logstash/logs:/app/logs'
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:8.1.0
    container_name: logstash
    env_file:
      - path: ./env/.env
        required: true
    ports: [ '9600:9600' ]
    depends_on: [ 'elasticsearch' ]
    volumes:
      - './volumes/logstash/pipeline:/usr/share/logstash/pipeline:rw'
      - './volumes/logstash/logs:/logs:rw'

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.1.0
    container_name: filebeat
    env_file:
      - path: ./env/.env
        required: true
    user: root
    volumes:
      - './volumes/filebeat/log:/var/log/:ro'
      - './volumes/filebeat/docker.sock:/var/run/docker.sock'
      - './volumes/filebeat/logs/:/var/lib/docker/containers/logs:ro'
      - './volumes/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml'
    command: [ "--strict.perms=false" ]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.0
    container_name: kibana
    env_file:
      - path: ./env/.env
        required: true
    ports: [ '5601:5601' ]
    depends_on:
      - elasticsearch